services:
  api:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - 8888:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  redis:
    image: redis
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
